Write to file
graceolivia/Chartify2000 pull request #16
Opened 2021-11-02 18:00 UTC by graceolivia

Added the ability to write to a file! It will automatically go in the new `Charts` folder.

2021-11-02 18:54 UTC, breadoliveoilsalt commented on Sources/SwiftCli/main.swift
> +        let writeToFile = WriteToFile()
Perhaps a name change to `FileWriter`?

2021-11-02 18:57 UTC, breadoliveoilsalt commented on Tests/SwiftCliCoreTests/ChartifyTest.swift
> +
I like where these are.  Nice job.  Small nit: no need to include `Mock` in the description of the test (function name).

2021-11-02 18:58 UTC, breadoliveoilsalt commented on Sources/SwiftCliCore/WriteToFile.swift
> +                            atomically: true,
Looks like a wrapper 👍

2021-11-03 17:02 UTC, hnlee requested changes

2021-11-03 17:02 UTC, hnlee commented on Sources/SwiftCliCore/Chartify.swift
> +    public func run(userInput: [String], file: String? = nil, knitFlat: Bool = false, fileNameToWrite: String? = nil) {
Also nonblocking for this PR but: does `Chartify` need to know or care about what output file name to write to? Or is that something that it makes more sense for `FileWriter` to know?

2021-11-03 17:02 UTC, hnlee commented on Sources/SwiftCliCore/Chartify.swift
> +                print(chart) }
Looks good but maybe worth extracting into its own private method.

2021-11-04 16:21 UTC, graceolivia commented on Sources/SwiftCliCore/Chartify.swift
> +                print(chart) }
Done!

2021-11-04 20:24 UTC, hnlee requested changes
Some naming changes requested, but after that it should be good to merge.

2021-11-04 20:24 UTC, hnlee commented on Tests/SwiftCliCoreTests/ChartifyTest.swift
> +class MockWriteToFile: FileWriter {
Calling it `MockFIleWriter` makes it clearer what you're mocking.

2021-11-04 20:24 UTC, hnlee commented on Tests/SwiftCliCoreTests/ChartifyTest.swift
> +        wasWriteToFileCalled = true
Having naming consistency, e.g. `wasWriteFileCalled`, makes it clearer which method you're checking.

2021-11-04 20:24 UTC, hnlee commented on Sources/SwiftCliCore/Chartify.swift
> +    private func returnChartInPrefferedFormat(chart: String, fileNameToWrite: String?) throws {
Typo in the name here

2021-11-05 13:54 UTC, merged